name: CI Pipeline

on:
  push:
    branches:
      - main

# Add permissions for GITHUB_TOKEN
permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="rivallar/hw20"
          VERSION=$(date +'%Y%m%d%H%M%S')  # Using timestamp as version
          docker build -t $IMAGE_NAME:$VERSION .
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$VERSION

      - name: Checkout CD repository
        uses: actions/checkout@v2
        with:
          repository: ruslan-rusanovich/CD_part
          token: ${{ github.token }}
          path: cd-repo

      - name: Update Kubernetes manifest
        run: |
          cd cd-repo
          # Update the image tag in the manifest using sed
          sed -i "s|$IMAGE_NAME:.*|$IMAGE_NAME:$VERSION|" kubernetes_deployments/fastapi_manifest.yml

      - name: Commit and push changes
        run: |
          cd cd-repo
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add kubernetes_deployments/fastapi_manifest.yml
          git commit -m "Update image tag to $VERSION"
          git push
